---
# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/
wordpress_sites:
  abundanthousingma.org:
    site_hosts:
      - canonical: abundanthousingma.org
        redirects:
          - www.abundanthousingma.org
    local_path: ../site
    admin_email: info@abundanthousingma.org
    branch: main
    repo: git@github.com:abundanthomesma/abundanthousingma.org.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      stapling_enabled: false
      provider: cloudflare-origin-ca
    cache:
      enabled: false
    cloudflare-origin-ca:
      hostnames:
        - abundanthousingma.org
        - '*.abundanthousingma.org'
