# Created by trellis-cli v0.9.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  abundanthousingma.org:
    site_hosts:
      - canonical: stage.abundanthousingma.org
    local_path: ../site
    branch: official-site
    repo: git@github.com:abundanthomesma/abundanthousingma.org.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
