---
name: Lint

on:
  push:
    branches:
      - official-site

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: cd site/web/app/themes/abundanthousingma && npm ci
      - run: cd site/web/app/themes/abundanthousingma && npm run build --if-present
      - run: cd site/web/app/themes/abundanthousingma && npm test
