---
name: Lint

"on": push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - run: cd site/web/app/themes/abundanthousingma && yarn
      - run: cd site/web/app/themes/abundanthousingma && yarn build
      - run: cd site/web/app/themes/abundanthousingma && yarn test
